### ISSUE TITLE
contact page do not show data in iOS real device

### ISSUE THREAD

**Issue by andreavitiani** [andreavitiani/cv0app#3]
In the "contact" page, the app should show the bluetooth broadcasting infos from device nearby.

Condition
The app is installed in a real device
Bluetooth is on
Other device in the range broadcasting advertising are present and verified with other apps

**Comment by andreavitiani** [comment]
![IMG_1231 2](https://user-images.githubusercontent.com/21630867/79119722-564f7800-7d91-11ea-86b0-c65c8e955016.PNG)

**Comment by pavelvolynets** [comment]
fixed
