### ISSUE TITLE
Navigation glitch

### ISSUE THREAD

**Issue by andreavitiani** [andreavitiani/cv0app#4]
During navigation to "contacts page" from any page, the "contact page" get partially stuck on the left.

**Comment by andreavitiani** [comment]
![IMG_1231 2](https://user-images.githubusercontent.com/21630867/79119805-826af900-7d91-11ea-9dc0-450c7a3747d2.PNG)

**Comment by andreavitiani** [comment]
![IMG_E233AD04514B-1](https://user-images.githubusercontent.com/21630867/79119854-a0385e00-7d91-11ea-803e-2301828488a9.jpeg)

**Comment by pavelvolynets** [comment]
fixed in the master
